### ISSUE TITLE
Some issues occurred during the installation of CoMeT

### ISSUE THREAD

**Issue by yixian7777777** [marg-tools/CoMeT#1]
Dear authors,
   I met some issues concerning installing CoMeT and the major issues are shown below.
### **1. The python-matplotlib version is depreciated in python2 as shown in Installation phase.**
 I tried to install the python-matplotlib using the command _sudo apt-get python-matplotlib_, but I failed many times and it always showed the error below:
![image](https://user-images.githubusercontent.com/30893462/132250552-d1c07f68-c275-4b27-b20a-19beaa395daf.png)

 I change this version to python3-matplotlib, it works. But I am not sure if the python3-matplotlib is compatible with the whole project.

### **2.  The lack of hotspot_c_tool folder in the source code as shown in Compile phase**
In your guide, it exhibits that we should compile the hotspot_c_tool for core temperature estimation. However, there is no such hotspot_c_folder in the source code.
![image](https://user-images.githubusercontent.com/30893462/132250983-f66bed97-5429-48b0-868e-9a07a3fad3be.png)

### **3.  The unclear configuration instruction as shown in Compile phase**
 I do not know which config file I should search and operate when I follow the guide “Configure the path of the hotspot tool and config directory in the configure file(search for tool_path and config_path variables)”. 
I am not aware of what it takes to configure the path of the hotspot tool and config directory in the config file. Indeed, I use the command _grep -r "tool_path"_ and _grep -r "config_path"_ to find the relevant content, but I still don't know what I am supposed to do next.
![image](https://user-images.githubusercontent.com/30893462/132251527-916dc6f3-a2c8-4830-9631-8b2a85bb1362.png)

Consequently, the demo didn’t work and it gives me hints saying there were some configure issues in the config.cpp file. I search the relevant contents in that config.cpp file. I assumed there are some issues in the configure process.
![image](https://user-images.githubusercontent.com/30893462/132251567-3a207261-f646-43e6-9c1d-12e87e17c1d0.png)
 
I am looking forward to your reply.

Best wishes
Yixian

**Comment by siddhulokesh** [comment]
Hi Yixian

Thanks for your clear description of the questions. Posting initial replies:
_____________________________

1. Please use the following steps (updated) to install CoMeT. 

- CoMeT compiles and runs inside a Docker container. Therefore, we need to download & install Docker. For more info: https://docs.docker.com/engine/install/ubuntu/

- After installing Docker, please do:

cd docker
make 
make run 
cd .. 

If you get a warning "docker groups: cannot find name for group id 1000", please ignore the same.

- Compiling Sniper

make # or use 'make -j N' where N is the number of cores in your machine to use parallel make

- Compiling HotSpot

cd hotspot_tool/
make
cd ..

2. Recently, we had updated the code so that we can obtain core temperatures using hotspot_tool.
hotspot_c_tool is not needed now and hence, removed.

3. I am not too sure if the compilation of CoMeT was completed successfully. Once done, please check the config file: config/gainestown_3D.cfg. And, then, you could run the following test case:

cd test/thermal_example/
make run
_____________________________

We will be doing a comprehensive update of readme in the coming week. Will keep you posted.

Thanks
Lokesh Siddhu
Ph.D. student, CSE IIT Delhi  
https://www.cse.iitd.ac.in/~siddhulokesh/

**Comment by yixian7777777** [comment]
Thanks for your reply.
I followed your instruction and re-install the CoMeT in docker.  Unfortunately, I encountered a new bug, as shown below:
![image](https://user-images.githubusercontent.com/30893462/132258409-22b54dcf-7063-46fe-a672-765f4f403fc3.png)
I checked the sniper.py, it mentioned the sniper.py was generated automatically. I also check the Makefile. But I have no idea to modify the Makefile.
 I guess that maybe some authentication problems exist at the beginning of creating the docker images. Hence, I checked the Makefile in the docker folder. Nevertheless,  it has been utilized the privileged root.
![image](https://user-images.githubusercontent.com/30893462/132258493-50a7e569-17a9-4c83-a120-ef4758361eec.png)

**Comment by kediarajesh** [comment]
Hi Yixian,
Just wanted to confirm - since you had already compiled the code earlier in the same directory without docker, did you do a make clean in the /home/yixian/CoMeT folder before/after invoking the docker run command? If not, could you please do it and try again? We saw this issue earlier and it went away with make clean.

--rajesh

**Comment by yixian7777777** [comment]
Hi Rajesh,
   Thanks for your reply.
   It seems work fine.
![image](https://user-images.githubusercontent.com/30893462/132295971-09217bc8-f0f2-4261-bc3d-e385037f707f.png)

**Comment by kediarajesh** [comment]
Hi Yixian,
Great to hear that it worked at your end. Please feel free to ask if you come across any questions. Hope you find the tool useful. I am closing this issue now.

--rajesh

**Comment by yixian7777777** [comment]
Thanks

Best wishes
Yixian
