### ISSUE TITLE
FileNotFindError : not such file or direction :  benchmark/combined_rvalue.trace

### ISSUE THREAD

**Issue by XieJiayan** [marg-tools/CoMeT#17]
Dear sir,
I have made the docker image version-16.04 compiling the sniper and hotspot successfully. Then I compile in the direction CoMeT/benchmark/, getting  the image below:

![image](https://github.com/marg-tools/CoMeT/assets/84165730/8178de89-9a24-4a79-95d5-e6818f01387f)

Then I enter the direction: simulationcontrol and  python3 run.py the default example  , getting the the error below.  I did not find a solution to resolve it.

![image](https://github.com/marg-tools/CoMeT/assets/84165730/c98db4b0-2731-4f04-ac99-0583bf7fed13)

Hope to get your reply, thanks!
Yours sincerely

**Comment by XieJiayan** [comment]
I once guessed that it was the network problem that caused me to fail to download the relevant benchmark when I made benchmark. But when I joined the Princeton Network Agency, the problem still arose. So my solution was wrong.

**Comment by spolstra** [comment]
Hi XieJiayan,

The default docker is ubuntu 20.04. Why did you decide to use the 16.04 version?

The main Makefile (naively) assumes that it's running in ubuntu 20.04:
```
hotsniper-reliability:
    @git submodule update --init hotsniper-reliability || echo "Warning: cannot retrieve $@ submodule"
    @make -f Makefile.ubuntu-20.04 -C hotsniper-reliability/ || echo "Warning: cannot compile the $@ submodule"
```
So I suspect that it failed to compile the `hotsniper-reliability` code and that is why it cannot find the rvalue trace files. There is a makefile for ubuntu 16.04 in the `hotsniper-reliability` directory so you can edit the Makefile to use that one:
```
hotsniper-reliability:
    @git submodule update --init hotsniper-reliability || echo "Warning: cannot retrieve $@ submodule"
    @make -f Makefile.ubuntu-16.04 -C hotsniper-reliability/ || echo "Warning: cannot compile the $@ submodule"
```

I haven't tested this on CoMet, but it should work.

So either redo  the whole CoMet installation with the ubuntu 20.04 docker or try to edit the main makefile so that the `hotsniper-reliability` module is compiled with the ubuntu 16.04 make file as shown above.

Regards,

Simon

**Comment by XieJiayan** [comment]
Dear sir,
Thank you so much for your recovery. 
After receiving your message, I quickly reviewed the code of the relevant file, and after many attempts. It took me some time to pinpoint my mistakes and try more.
I found that the problem was indeed the hotsniper-reliabitity path as you said.But the problem is not using Makefile.ubuntu.20.04 or Makefile.ubuntu.16.04. I found that after compile sniper in ubuntu16.04, the corresponding hotsniper-reliabitity path file could not be generated. The hotsniper-reliability command in the sinper makefile cannot be executed.

After many attempts, I take the  advice , gave up the version 16.04 and switched to version 20.04.
You asked me earlier why I didn't use version 20.04, because I couldn't solve the benchmark compilation problem several times before.
1. sniper(hotsniper-reliability) was successfully compiled in version 20.04.
2. hotspot-tools is successfully compiled in version 20.04.
3. There is a problem when compiling benchmark in version 20.04, which seems to be related to the use of the compiler after my query. This was very confusing to me, because I was working in docker, and such error messages should not happen.

Image: Errors related to parsec compilation.
![image](https://github.com/marg-tools/CoMeT/assets/84165730/eb55b3f0-d150-4ef0-9893-f5cae2f96501)


I have a partner who learned about CoMeT and used it four months ago. He showed me the ubuntu-sniper-20.04 docker image on his computer and the CoMeT file he git-clone four months ago. However, he encountered the same problem (which he said he had never encountered before ).

Regards,

Xie JiaYan

**Comment by spolstra** [comment]
Hi Xie JiaYan,

Thanks for your reply. I can reproduce that benchmark compilation error on my system. It happens during the compilation of the parsec2-raytrace benchmark that is not used in CoMeT. So the quick solution is to just run `make` again. It will continue the compilation of the other benchmarks.

I have only worked on the reliability model and not on CoMeT itself. I don't know when this problem was introduced but will forward it the current maintainers.

And when I have time I will test the reliability model on the ubuntu 16.04 docker and fix it if needed.

Regards,

Simon
