### ISSUE TITLE
Very low power consumption of memory banks compared to processor's cores

### ISSUE THREAD

**Issue by SobhanNiknam** [marg-tools/CoMeT#2]
Dear CoMeT Developers,

I've conducted a few experiments using CoMeT. Looking at the combined_power.trace which is shown below, I wonder why the power consumption of memory banks is extremely lower than the cores' power consumption and why some of them are even zero? I see that some extra leakage power, but not dynamic power, is calculated for each memory bank wrt. its temperature in HotSpot. But then, considering the power numbers in the trace below, I wonder where does the dynamic power consumption (above 0.3W) which is shown in figure 4 of your article published in Arxiv come from?

Best Regards,
Sobhan Niknam
[combined_power.txt](https://github.com/marg-tools/CoMeT/files/8169362/combined_power.txt)

**Comment by kediarajesh** [comment]
Dear Sobhan,
Thanks for using CoMeT and for the query. 
Regarding your query on the memory, power being small in your experiments and it being above 0.3W in Fig. 4 in the article - this is because Fig. 4 was generated assuming a full activity at the 3D memory banks. It has been generated using data directly from CACTI-3DD without any integrated simulation. The energy-per-access obtained from CACTI-3DD was converted to dynamic power, assuming an activity factor of 1. Leakage power was obtained by varying the temperature in the CACTI-3DD config file. 
You might use the _16core cfg files (available for 2D-ext, 3D-ext, 3D-stacked, and 2.5D) available in the repo, and it should give you higher power than the default 4-core configuration due to increased activity.

To answer your other query related to the attached combined power file and higher core power, I would need more information about your setup - which configuration (2D-ext, 3D-ext, 3D-stacked, and 2.5D) are you using, which workload are you executing, technology node, etc.

Regards,
Rajesh
